all clean:
	$(MAKE) DEBUG=NO -f ../Src/example-1.mk $@
	$(MAKE) DEBUG=NO -f ../Src/example-2.mk $@
	$(MAKE) DEBUG=NO -f ../Src/example-3.mk $@
	$(MAKE) DEBUG=NO -f ../Src/example-4.mk $@
	$(MAKE) DEBUG=NO -f ../Src/example-5.mk $@
	$(MAKE) DEBUG=NO -f ../Src/example-6.mk $@
	$(MAKE) DEBUG=NO -f ../Src/example-7.mk $@
