all clean:
	$(MAKE) DEBUG=YES -f ../Src/example-1.mk $@
	$(MAKE) DEBUG=YES -f ../Src/example-2.mk $@
	$(MAKE) DEBUG=YES -f ../Src/example-3.mk $@
	$(MAKE) DEBUG=YES -f ../Src/example-4.mk $@
	$(MAKE) DEBUG=YES -f ../Src/example-5.mk $@
