messip: messip_lib.c File Reference
messip_lib.c File Reference
MessIP : Message Passing over TCP/IP Copyright (C) 2001-2007 Olivier Singla http://messip.sourceforge.net/.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <assert.h>
#include <fcntl.h>
#include <stdarg.h>
#include "messip.h"
#include "messip_private.h"
#include "messip_utils.h"
Data Structures
struct list_connect_s
struct messip_timer_s
Typedefs
typedef struct list_connect_s list_connect_t
typedef struct messip_timer_s messip_timer_t
Functions
void messip_init (void)
The messip_init() initialize the library, and must be called prior to any call of other functions of he library (likely messip_connect).
int messip_writev (SOCKET sockfd, const struct iovec *iov, int iovcnt)
Write data from multiple buffers over a TCP socket.
int messip_readv (SOCKET sockfd, const struct iovec *iov, int iovcnt)
Read data into multiple buffers from a TCP socket.
int messip_select (int fd, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
TBD.
messip_cnx_t * messip_connect (char *mgr_ref, messip_id_t id, int msec_timeout)
Connection to the messip manager (messip_mgr)
int messip_disconnect (messip_cnx_t *cnx, int msec_timeout)
Delete the connection with the messip manager (messip_mgr)
messip_channel_t * messip_channel_create (messip_cnx_t *cnx, const char *name, int msec_timeout, int32_t maxnb_msg_buffered)
Enables a server to create a channel.
int messip_channel_delete (messip_channel_t *ch, int msec_timeout)
Enables a server to delete a channel that was previously created by messip_channel_create()
messip_channel_t * messip_channel_connect (messip_cnx_t *cnx, const char *name, int msec_timeout)
Enables a client to connect to a channel owned by a server.
int messip_channel_disconnect (messip_channel_t *ch, int msec_timeout)
Enables a client to disconnect from a channel owned by a server.
int messip_channel_ping (messip_channel_t *ch, int msec_timeout)
TBD.
static int ping_reply (messip_channel_t *ch, int index, int msec_timeout)
TBD.
static int reply_to_thread_client_send_buffered_msg (messip_channel_t *ch, SOCKET sockfd, int msec_timeout)
TBD.
int messip_receive (messip_channel_t *ch, int32_t *type, void *rec_buffer, int maxlen, int msec_timeout)
Enables a server to receive messages sent on a channel owned by this server.
int messip_send (messip_channel_t *ch, int32_t type, void *send_buffer, int send_len, int32_t *answer, void *reply_buffer, int reply_maxlen, int msec_timeout)
Enables a client to send a synchronous message to a channel owned by a server.
int32_t messip_buffered_send (messip_channel_t *ch, int32_t type, void *send_buffer, int send_len, int msec_timeout)
Enable a client to send an Asynchronous Message to a server.
int messip_reply (messip_channel_t *ch, int index, int32_t answer, void *reply_buffer, int reply_len, int msec_timeout)
Enables a server to reply to a client that has sent a messages to a channel owned by this server The client was blocked on the messip_send() function, and the messip_reply() function will unblock the client.
static int messip_timer_send (messip_channel_t *ch, int32_t type, int msec_timeout)
TBD.
int32_t messip_death_notify (messip_cnx_t *cnx, int status, int msec_timeout)
TBD.
void messip_set_log_level (unsigned level)
TBD.
unsigned messip_get_log_level (void)
TBD.
int messip_log (unsigned level, const char *fmt,...)
TBD.
Variables
static list_connect_t * list_connect
TBD.
static int nb_list_connect
TBD.
static unsigned log_level = MESSIP_LOG_ERROR | MESSIP_LOG_WARNING
TBD.
Detailed Description
MessIP : Message Passing over TCP/IP Copyright (C) 2001-2007 Olivier Singla http://messip.sourceforge.net/.
This is the library that encapsulate the communication with the manager (messip_mgr). The library also implements send/receive/reply because the manager is not then involved (unless it's a buffered message).
Definition in file messip_lib.c.
Typedef Documentation
typedef struct list_connect_s list_connect_t
typedef struct messip_timer_s messip_timer_t
Function Documentation
void messip_init (void)
The messip_init() initialize the library, and must be called prior to any call of other functions of he library (likely messip_connect).
Note
This function must be called only once per process, namely from the main thread.
See Also
messip_disconnect(), messip_channel_create(), messip_channel_disconnect()
Definition at line 123 of file messip_lib.c.
References nb_list_connect.
int messip_writev (SOCKET sockfd, const struct iovec * iov, int iovcnt)
Write data from multiple buffers over a TCP socket.
The main difference with the library function is that this function handles EINTR (signal received while receiving data).
Parameters
sockfd Socket file descriptor
iov pointer vector points to a struct iovec defining address and bytes
iovcnt Number of blocks described into vector iov
Returns
On success, returns the number of bytes written
On error, -1 is returned, and errno is set appropriately
Definition at line 141 of file messip_lib.c.
Referenced by messip_buffered_send(), messip_channel_connect(), messip_channel_create(), messip_channel_delete(), messip_channel_disconnect(), messip_channel_ping(), messip_connect(), messip_death_notify(), messip_reply(), messip_send(), messip_timer_send(), ping_reply(), and reply_to_thread_client_send_buffered_msg().
int messip_readv (SOCKET sockfd, const struct iovec * iov, int iovcnt)
Read data into multiple buffers from a TCP socket.
The main difference with the library function is that this function handles EINTR (signal received while receiving data).
Parameters
sockfd Socket file descriptor
iov pointer vector points to a struct iovec defining address and bytes
iovcnt Number of blocks described into vector iov
Returns
On success, returns the number of bytes read
On error, -1 is returned, and errno is set appropriately
Definition at line 172 of file messip_lib.c.
Referenced by messip_buffered_send(), messip_channel_connect(), messip_channel_create(), messip_channel_delete(), messip_channel_disconnect(), messip_channel_ping(), messip_connect(), messip_death_notify(), messip_receive(), and messip_send().
int messip_select (int fd, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval * timeout)
TBD.
Parameters
fd TBD
readfds TBD
writefds TBD
exceptfds TBD
timeout TBD
Returns
TBD
Definition at line 200 of file messip_lib.c.
messip_cnx_t* messip_connect (char * mgr_ref, messip_id_t id, int msec_timeout)
Connection to the messip manager (messip_mgr)
Parameters
mgr_ref mgr_ref can be
NULL: in this case:
Either the file /etc/messip exists an contains the IP address or host;
Or specify a host or IP address to designate the node where the messip manager is running.
Or if the file /etc/messip does not exist, “localhost” is then used.
id task identifier, which is used only for information. This is a string of up to 8 characters.
msec_timeout if not 0, is a timeout (expressed in milliseconds) where the function exits if connection with the messip manager fails.
Returns
A pointer to a messip_cnx_t structure (that will be used next on a channel creation or connection), or -1 if an error occurred (errno is set).
ETIMEDOUT Occurs if the messip manager did not answer the connection request within the provided time.
Note
From the same thread, only one connection to the messip manager will be allowed.
See Also
messip_disconnect(), messip_channel_create(), messip_channel_disconnect()
Definition at line 230 of file messip_lib.c.
References closesocket, messip_send_connect_t::id, IDCPY, MESSIP_DEFAULT_PORT, MESSIP_NOTIMEOUT, MESSIP_OK, MESSIP_OP_CONNECT, messip_readv(), messip_writev(), messip_reply_connect_t::ok, read_etc_messip(), messip_cnx::remote_id, and messip_cnx::sockfd.
int messip_disconnect (messip_cnx_t * cnx, int msec_timeout)
Delete the connection with the messip manager (messip_mgr)
Parameters
cnx is the connection (to the messip manager) structure which was returned by messip_connect()
msec_timeout if not 0, is a timeout (expressed in milliseconds) where the function exits if connection with the messip manager fails.
Returns
0 ir no error, or -1 if an error occurred (errno is set).
ETIMEDOUT Occurs if the messip manager did not answer the connection request within the provided time.
Todo:
Function not yet implemented
Definition at line 396 of file messip_lib.c.
messip_channel_t* messip_channel_create (messip_cnx_t * cnx, const char * name, int msec_timeout, int32_t maxnb_msg_buffered)
Enables a server to create a channel.
In order for a server to receive messages (see messip_receive), a server must first create a channel. A client who wants to send a message to this server will first connect to this channel (using messip_channel_connect), then will send the message on it (using messip_send). A channel is identified by a name, which must be unique. Note that messip_channel_create must be called only by a server (receiving messages), but not by a client (sending messages).
Parameters
cnx is the connection (to the messip manager) structure which was returned by messip_connect()
name is a name that identify the channel. This name must be unique.
msec_timeout if not 0, is a timeout (expressed in milliseconds) where the function exits if connection with the messip manager fails.
maxnb_msg_buffered specify the maximum number of Asynchronous messages that can be buffered by the messip manager. It’s valid to specify a value of 0: in this case, sending an Asynchronous message on this channel will not be allowed, and therefore will fail.
Returns
A pointer to a messip_channel_t structure (that will be used next when waiting messages from this channel), or -1 if an error occurred (errno is then set):
ETIMEDOUT : Occurs if the messip manager did not answered the connection request within the expressed time.
Note
Names of the channel must be unique, across the whole network.
See Also
messip_channel_delete(), messip_channel_connect(), messip_receive()
Definition at line 427 of file messip_lib.c.
References messip_send_channel_create_t::channel_name, closesocket, messip_channel_t::cnx, messip_send_channel_create_t::id, IDCPY, messip_send_channel_create_t::maxnb_msg_buffered, MESSIP_CHANNEL_NAME_MAXLEN, messip_log(), MESSIP_LOG_INFO, MESSIP_NOK, MESSIP_NOTIMEOUT, MESSIP_OP_CHANNEL_CREATE, messip_readv(), messip_writev(), messip_channel_t::name, messip_channel_t::nb_replies_pending, messip_channel_t::new_sockfd, messip_channel_t::new_sockfd_sz, messip_reply_channel_create_t::ok, messip_channel_t::receive_allmsg, messip_channel_t::receive_allmsg_sz, messip_channel_t::recv_sockfd, messip_channel_t::recv_sockfd_sz, messip_cnx::remote_id, messip_channel_t::remote_id, messip_channel_t::send_sockfd, messip_reply_channel_create_t::sin_addr, messip_channel_t::sin_addr, messip_send_channel_create_t::sin_addr_str, messip_reply_channel_create_t::sin_addr_str, messip_channel_t::sin_addr_str, messip_send_channel_create_t::sin_port, messip_reply_channel_create_t::sin_port, messip_channel_t::sin_port, and messip_cnx::sockfd.
int messip_channel_delete (messip_channel_t * ch, int msec_timeout)
Enables a server to delete a channel that was previously created by messip_channel_create()
Parameters
ch Channel connection (to the server) structure which was returned by messip_channel_connect()
msec_timeout if not 0, is a timeout (expressed in milliseconds) where the function exits if connection with the messip manager fails.
Returns
If the operation succeed, the value 0 is returned.
If the operation timeout, the value –1 is returned and then errno is set:
ETIMEDOUT Occurs if the messip manager did not answered the channel deletion request within the expressed time
If the deletion can’t occur because of an active connection, the number of clients currently connected to this channel is then return.
Note
Only channels with no active connection on it (see messip_channel_connect) are allowed to be deleted.
See Also
messip_channel_create(), messip_channel_connect(),messip_receive()
Definition at line 574 of file messip_lib.c.
References messip_channel_t::cnx, messip_send_channel_delete_t::id, IDCPY, messip_log(), MESSIP_LOG_INFO, MESSIP_NOTIMEOUT, MESSIP_OP_CHANNEL_DELETE, messip_readv(), messip_writev(), messip_channel_t::name, messip_send_channel_delete_t::name, messip_reply_channel_delete_t::nb_clients, messip_channel_t::remote_id, and messip_cnx::sockfd.
messip_channel_t* messip_channel_connect (messip_cnx_t * cnx, const char * name, int msec_timeout)
Enables a client to connect to a channel owned by a server.
Prior to send any message to a server, this operation must be performed by a client.
messip_channel_connect must be called only by a client (sending messages), but not by a server (receiving messages). It’s perfectly valid to have the same process acting both as server and client: in this case, there will be a thread for the server, and another thread for the client.
Parameters
cnx connection (to the messip manager) structure which was returned by messip_connect()
name name that identify the channel you want to connect to. This name is unique.
msec_timeout if not 0, is a timeout (expressed in milliseconds) where the function exits if connection with the messip manager fails.
Returns
A pointer to a messip_channel_t structure (that will be used next when sending messages on this channel), or -1 if an error occurred (errno is then set):
ETIMEDOUT occurs if either the messip manage and the server owning the channel did not answered the connection request within the expressed time.
Note
Only one active connection to the same channel can be performed by a given thread.
See Also
messip_channel_create(), messip_channel_disconnect(), messip_receive(), messip_send()
Definition at line 659 of file messip_lib.c.
References closesocket, messip_channel_t::cnx, messip_channel_t::f_already_connected, messip_reply_channel_connect_t::f_already_connected, messip_send_channel_connect_t::id, messip_reply_channel_connect_t::id, IDCPY, list_connect_s::info, MESSIP_CHANNEL_NAME_MAXLEN, MESSIP_FLAG_CONNECTING, messip_log(), MESSIP_LOG_INFO, MESSIP_NOK, MESSIP_NOTIMEOUT, MESSIP_OP_CHANNEL_CONNECT, messip_readv(), messip_writev(), messip_channel_t::mgr_sockfd, messip_reply_channel_connect_t::mgr_sockfd, messip_channel_t::name, messip_send_channel_connect_t::name, nb_list_connect, messip_reply_channel_connect_t::ok, messip_cnx::remote_id, messip_channel_t::remote_id, messip_channel_t::send_sockfd, messip_channel_t::sin_addr, messip_reply_channel_connect_t::sin_addr, messip_channel_t::sin_addr_str, messip_reply_channel_connect_t::sin_addr_str, messip_channel_t::sin_port, messip_reply_channel_connect_t::sin_port, and messip_cnx::sockfd.
int messip_channel_disconnect (messip_channel_t * ch, int msec_timeout)
Enables a client to disconnect from a channel owned by a server.
Note
No exchange is performed with the server (the owner of the channel), but only with the messip manager.
messip_channel_disconnect must be called only by a client (sending messages), but not by a server (receiving messages
Parameters
ch channel connection (to the server) structure which was returned by messip_channel_connect()
msec_timeout if not 0, is a timeout (expressed in milliseconds) where the function exits if the connection with the messip manager fails.
Returns
A pointer to a messip_channel_t structure (that will be used next when sending messages on this channel), or -1 if an error occurred (errno is then set):
ETIMEDOUT occurs if either the messip manage and the server owning the channel did not answered the connection request within the expressed time.
See Also
messip_channel_create(), messip_channel_disconnect(), messip_receive(), messip_send()
Definition at line 832 of file messip_lib.c.
References messip_channel_t::cnx, IDCPY, MESSIP_FLAG_DISCONNECTING, messip_log(), MESSIP_LOG_INFO, MESSIP_MSG_TIMEOUT, MESSIP_NOTIMEOUT, MESSIP_OP_CHANNEL_DISCONNECT, messip_readv(), messip_writev(), messip_channel_t::name, messip_reply_channel_disconnect_t::ok, messip_cnx::remote_id, messip_channel_t::send_sockfd, and messip_cnx::sockfd.
int messip_channel_ping (messip_channel_t * ch, int msec_timeout)
TBD.
Parameters
ch TBD
msec_timeout TBD
Returns
TBD
Definition at line 931 of file messip_lib.c.
References messip_channel_t::cnx, messip_datasend_t::datalen, messip_datasend_t::flag, messip_datasend_t::id, messip_datareply_t::id, IDCPY, MESSIP_FLAG_PING, messip_log(), MESSIP_LOG_ERROR, MESSIP_LOG_INFO, MESSIP_MSG_TIMEOUT, MESSIP_NOTIMEOUT, messip_readv(), messip_writev(), messip_cnx::remote_id, messip_channel_t::remote_id, messip_channel_t::send_sockfd, and messip_datasend_t::type.
static int ping_reply (messip_channel_t * ch, int index, int msec_timeout) static
TBD.
Parameters
ch TBD
index TBD
msec_timeout TBD
Returns
TBD
Definition at line 1005 of file messip_lib.c.
References IDCPY, messip_log(), MESSIP_LOG_INFO_VERBOSE, MESSIP_MSG_TIMEOUT, MESSIP_NOTIMEOUT, messip_writev(), messip_channel_t::new_sockfd, and messip_channel_t::remote_id.
Referenced by messip_receive().
static int reply_to_thread_client_send_buffered_msg (messip_channel_t * ch, SOCKET sockfd, int msec_timeout) static
TBD.
Parameters
ch TBD
sockfd TBD
msec_timeout TBD
Returns
TBD
Definition at line 1050 of file messip_lib.c.
References IDCPY, MESSIP_MSG_TIMEOUT, MESSIP_NOTIMEOUT, messip_writev(), and messip_channel_t::remote_id.
Referenced by messip_receive().
int messip_receive (messip_channel_t * ch, int32_t * type, void * rec_buffer, int maxlen, int msec_timeout)
Enables a server to receive messages sent on a channel owned by this server.
Note that this is a blocking function, i.e. the client is blocked until not only the server has received the message, but also until the server has replied to the client (see messip_reply).
If the message requires a reply, the value returned by messip_receive should then be used as parameter when using messip_reply.
Parameters
ch channel connection (to the server) structure which was returned by messip_channel_connect()
type 32-bits numbers that can be used optionally to identify the kind of message sent to the serve.
rec_buffer pointer to the buffer where the message sent will be stored. If set to an address of a pointer and if max_len is set to 0, then the buffer is dynamically allocated, it then will have to be free-ed later.
maxlen maximum length of the message that can be stored in the receiving buffer. If the server has sent more bytes, the whole call is failing.
msec_timeout if not 0, is a timeout (expressed in milliseconds) where the function exits if connection with the messip manager fails.
Returns
A status of the operation:
-1 if an error occurred (errno is then set).
MESSIP_MSG_DISCONNECT: the client has called messip_channel_disconnect
MESSIP_MSG_DISMISSED: the connection between the client and the server has been broken. The main reason is that the client died
MESSIP_MSG_TIMEOUT: the operation timed out.
MESSIP_MSG_TIMER: a timer has been triggered on this channel.
MESSIP_MSG_NOREPLY: the message received was not an Asynchronous message, and therefore does not require a reply.
Any other value (i.e. >= 0) is the parameter to use with messip_reply or messip_receive_more:
ETIMEDOUT occurs if the client owning the channel did not received the message replied back within the expressed time.
ENOMEM out of memory.
EFAULT buffer points outside your accessible address space.
ECONNRESET Message has been received, but reply fails because the initial sender lost the connection with the server.
See Also
messip_channel_create(), messip_reply(), messip_receive_more(), messip_send()
Definition at line 1122 of file messip_lib.c.
References closesocket, messip_channel_t::datalen, messip_channel_t::datalenr, IDCPY, MESSIP_FLAG_BUFFERED, MESSIP_FLAG_CONNECTING, MESSIP_FLAG_DEATH_PROCESS, MESSIP_FLAG_DISCONNECTING, MESSIP_FLAG_DISMISSED, MESSIP_FLAG_PING, MESSIP_FLAG_TIMER, messip_log(), MESSIP_LOG_INFO, MESSIP_MSG_DISCONNECT, MESSIP_MSG_DISMISSED, MESSIP_MSG_NOREPLY, MESSIP_MSG_TIMEOUT, MESSIP_MSG_TIMER, MESSIP_NOK, MESSIP_NOTIMEOUT, messip_readv(), messip_channel_t::nb_replies_pending, messip_channel_t::new_sockfd, messip_channel_t::new_sockfd_sz, ping_reply(), messip_channel_t::receive_allmsg, messip_channel_t::receive_allmsg_sz, messip_channel_t::recv_sockfd, messip_channel_t::recv_sockfd_sz, messip_channel_t::remote_id, and reply_to_thread_client_send_buffered_msg().
int messip_send (messip_channel_t * ch, int32_t type, void * send_buffer, int send_len, int32_t * answer, void * reply_buffer, int reply_maxlen, int msec_timeout)
Enables a client to send a synchronous message to a channel owned by a server.
Note that this is a blocking function, i.e. the client is blocked until the server not only until the server has received the message, but also until the server has replied to the client.
Note
No exchange at all is performed with the messip manager, but only with the server (i.e.the process owning the channel).
messip_channel_send must be called only by a client (sending messages), but not by a server (receiving messages).
Parameters
ch channel connection (to the server) structure which was returned by messip_channel_connect()
type 32-bits number that can be used optionally to identify the kind of message sent to the server
send_buffer pointer to the message to send. Note it’s valid to specify NULL and send_len set to 0, in this case no message is sent (only the two 32-bits type codes).
send_len length of the message to be sent (can be 0).
answer 32-bit number that can be used optionally to identify the status or type of answer. Note that this pointer can be NULL.
reply_buffer pointer to a buffer where to store the answer sent back from the server. As an option, you can specify the address to a pointer and specify 0 for reply_maxlen, then the buffer will be dynamically allocated (you will have later to free it).
reply_maxlen Maximum length for the reply.
msec_timeout msec_timeout, if not 0, is a timeout (expressed in milliseconds) where the function exits if connection with the messip manager fails.
Returns
A pointer to a messip_channel_t structure (that will be used next when sending messages on this channel), or -1 if an error occurred (errno is then set):
ETIMEDOUT occurs if either the server owning the channel did not received and replied to the message within the expressed time.
See Also
messip_channel_create(), messip_channel_disconnect(), messip_receive(), messip_send()
Definition at line 1413 of file messip_lib.c.
References messip_datareply_t::answer, messip_channel_t::cnx, messip_channel_t::datalen, messip_datasend_t::datalen, messip_datareply_t::datalen, messip_channel_t::datalenr, messip_datasend_t::flag, messip_datasend_t::id, messip_datareply_t::id, IDCPY, messip_log(), MESSIP_LOG_INFO_VERBOSE, MESSIP_MSG_TIMEOUT, MESSIP_NOTIMEOUT, messip_readv(), messip_writev(), messip_cnx::remote_id, messip_channel_t::remote_id, messip_channel_t::send_sockfd, and messip_datasend_t::type.
int32_t messip_buffered_send (messip_channel_t * ch, int32_t type, void * send_buffer, int send_len, int msec_timeout)
Enable a client to send an Asynchronous Message to a server.
The server will buffer these messages, until the maximum number of buffered messages is reached. There is no reply from the server, therefore the client does not wait, unless the maximum number of buffered messages is reached.
Parameters
ch channel connection (to the server) structure which was returned by messip_channel_connect()
type 32-bits number that can be used optionally to identify the kind of message sent to the server
send_buffer pointer to the message to send. Note it’s valid to specify NULL and send_len set to 0, in this case no message is sent (only the two 32-bits codes).
send_len length of the message to be sent (can be 0).
msec_timeout if not 0, is a timeout (expressed in milliseconds) where the function exits if connection with the messip manager fails.
Returns
pointer to a messip_channel_t structure (that will be used next when sending messages on this channel), or -1 if an error occurred (errno is then set).
See Also
messip_channel_create(), messip_channel_disconnect(), messip_receive(), messip_send()
Definition at line 1564 of file messip_lib.c.
References messip_channel_t::cnx, messip_send_buffered_send_t::datalen, messip_send_buffered_send_t::id_from, IDCPY, messip_log(), MESSIP_LOG_INFO_VERBOSE, MESSIP_MSG_TIMEOUT, MESSIP_NOTIMEOUT, MESSIP_OP_BUFFERED_SEND, messip_readv(), messip_writev(), messip_channel_t::mgr_sockfd, messip_send_buffered_send_t::mgr_sockfd, messip_reply_buffered_send_t::nb_msg_buffered, messip_channel_t::remote_id, messip_cnx::sockfd, and messip_send_buffered_send_t::type.
int messip_reply (messip_channel_t * ch, int index, int32_t answer, void * reply_buffer, int reply_len, int msec_timeout)
Enables a server to reply to a client that has sent a messages to a channel owned by this server The client was blocked on the messip_send() function, and the messip_reply() function will unblock the client.
Parameters
ch channel connection (to the server) structure which was returned by messip_channel_connect()
index value previously returned by the messip_receive()
answer 32-bits number that can be used optionally to identify the kind of message sent back to the client.
reply_buffer pointer to the buffer where the message to be sent is stored. A NULL value is valid (as long as reply_len is set to 0).
reply_len length of the message to be sent. Note that 0 is a valid value (in this case reply_buffer should be set to NULL).
msec_timeout if not 0, is a timeout (expressed in milliseconds) where the function exits if connection with the client has failed.
Returns
A status of the operation:
MESSIP_NOK if an error occurred (errno is then set).
MESSIP_MSG_DISCONNECT: the client has called messip_channel_disconnect
MESSIP_MSG_DISMISSED: the connection between the client and the server has been broken. The principal reason is that the client died.
MESSIP_MSG_TIMEOUT:
MESSIP_OK if the reply function has successed.
See Also
messip_channel_create(), messip_reply(), messip_receive_more(), messip_send()
Definition at line 1653 of file messip_lib.c.
References messip_channel_t::cnx, IDCPY, messip_log(), MESSIP_LOG_INFO_VERBOSE, MESSIP_MSG_TIMEOUT, MESSIP_NOTIMEOUT, messip_writev(), messip_channel_t::nb_replies_pending, messip_channel_t::new_sockfd, messip_channel_t::receive_allmsg, messip_channel_t::receive_allmsg_sz, and messip_cnx::remote_id.
static int messip_timer_send (messip_channel_t * ch, int32_t type, int msec_timeout) static
TBD.
Parameters
ch TBD
type TBD
msec_timeout TBD
Returns
TBD
Definition at line 1715 of file messip_lib.c.
References messip_datasend_t::datalen, messip_datasend_t::flag, messip_datasend_t::id, IDCPY, MESSIP_FLAG_TIMER, messip_log(), MESSIP_LOG_INFO_VERBOSE, MESSIP_MSG_TIMEOUT, MESSIP_NOTIMEOUT, messip_writev(), messip_channel_t::remote_id, messip_channel_t::send_sockfd, and messip_datasend_t::type.
int32_t messip_death_notify (messip_cnx_t * cnx, int status, int msec_timeout)
TBD.
Parameters
cnx TBD
status TBD
msec_timeout TBD
Returns
TBD
Definition at line 1868 of file messip_lib.c.
References messip_send_death_notify_t::id_from, IDCPY, messip_log(), MESSIP_LOG_INFO, MESSIP_MSG_TIMEOUT, MESSIP_NOTIMEOUT, MESSIP_OP_DEATH_NOTIFY, messip_readv(), messip_writev(), messip_reply_death_notify_t::ok, messip_cnx::remote_id, messip_cnx::sockfd, and messip_send_death_notify_t::status.
void messip_set_log_level (unsigned level)
TBD.
Parameters
level TBD
Definition at line 1931 of file messip_lib.c.
References log_level.
unsigned messip_get_log_level (void)
TBD.
Returns
TBD
Definition at line 1940 of file messip_lib.c.
References log_level.
int messip_log (unsigned level, const char * fmt, ...)
TBD.
Parameters
level TBD
fmt TBD
... TBD
Returns
TBD
Definition at line 1952 of file messip_lib.c.
References log_level.
Referenced by messip_buffered_send(), messip_channel_connect(), messip_channel_create(), messip_channel_delete(), messip_channel_disconnect(), messip_channel_ping(), messip_death_notify(), messip_receive(), messip_reply(), messip_send(), messip_timer_send(), and ping_reply().
Variable Documentation
list_connect_t* list_connect static
TBD.
Definition at line 109 of file messip_lib.c.
int nb_list_connect static
TBD.
Definition at line 110 of file messip_lib.c.
Referenced by messip_channel_connect(), and messip_init().
unsigned log_level = MESSIP_LOG_ERROR | MESSIP_LOG_WARNING static
TBD.
Definition at line 112 of file messip_lib.c.
Referenced by messip_get_log_level(), messip_log(), and messip_set_log_level().