messip: messip_private.h File Reference
messip_private.h File Reference
MessIP : Message Passing over TCP/IP Copyright (C) 2001-2007 Olivier Singla http://messip.sourceforge.net/.
Data Structures
struct messip_mgr
struct messip_send_connect_t
struct messip_reply_connect_t
struct messip_send_channel_create_t
struct messip_reply_channel_create_t
struct messip_send_channel_delete_t
struct messip_reply_channel_delete_t
struct messip_send_channel_connect_t
struct messip_reply_channel_connect_t
struct messip_send_channel_disconnect_t
struct messip_reply_channel_disconnect_t
struct messip_send_channel_ping_t
struct messip_reply_channel_ping_t
struct messip_send_buffered_send_t
struct messip_reply_buffered_send_t
struct messip_send_death_notify_t
struct messip_reply_death_notify_t
struct messip_datasend_t
struct messip_datareply_t
Macros
#define SIGVAL_PTR sival_ptr
#define MESSIP_FLAG_CONNECTING 1
#define MESSIP_FLAG_DISCONNECTING 2
#define MESSIP_FLAG_DISMISSED 3
#define MESSIP_FLAG_TIMER 5
#define MESSIP_FLAG_BUFFERED 6
#define MESSIP_FLAG_PING 7
#define MESSIP_FLAG_DEATH_PROCESS 8
#define IDCPY(DST, SRC)
Typedefs
typedef struct messip_mgr messip_mgr_t
Enumerations
enum {
MESSIP_OP_CONNECT = 0x01010101, MESSIP_OP_CHANNEL_CREATE = 0x02020202, MESSIP_OP_CHANNEL_DELETE = 0x03030303, MESSIP_OP_CHANNEL_CONNECT = 0x04040404,
MESSIP_OP_CHANNEL_DISCONNECT = 0x05050505, MESSIP_OP_CHANNEL_PING = 0x06060606, MESSIP_OP_BUFFERED_SEND = 0x07070707, MESSIP_OP_DEATH_NOTIFY = 0x08080808,
MESSIP_OP_SIN = 0x09090909
}
Functions
int messip_writev (SOCKET sockfd, const struct iovec *iov, int iovcnt)
Write data from multiple buffers over a TCP socket.
int messip_readv (SOCKET sockfd, const struct iovec *iov, int iovcnt)
Read data into multiple buffers from a TCP socket.
Detailed Description
MessIP : Message Passing over TCP/IP Copyright (C) 2001-2007 Olivier Singla http://messip.sourceforge.net/.
Definition in file messip_private.h.
Macro Definition Documentation
#define SIGVAL_PTR sival_ptr
Definition at line 16 of file messip_private.h.
#define MESSIP_FLAG_CONNECTING 1
Definition at line 173 of file messip_private.h.
Referenced by messip_channel_connect(), and messip_receive().
#define MESSIP_FLAG_DISCONNECTING 2
Definition at line 174 of file messip_private.h.
Referenced by messip_channel_disconnect(), and messip_receive().
#define MESSIP_FLAG_DISMISSED 3
Definition at line 175 of file messip_private.h.
Referenced by messip_receive().
#define MESSIP_FLAG_TIMER 5
Definition at line 176 of file messip_private.h.
Referenced by messip_receive(), and messip_timer_send().
#define MESSIP_FLAG_BUFFERED 6
Definition at line 177 of file messip_private.h.
Referenced by messip_receive().
#define MESSIP_FLAG_PING 7
Definition at line 178 of file messip_private.h.
Referenced by messip_channel_ping(), and messip_receive().
#define MESSIP_FLAG_DEATH_PROCESS 8
Definition at line 179 of file messip_private.h.
Referenced by messip_receive().
#define IDCPY (DST, SRC)
Value:
strncpy(DST, SRC, MESSIP_MAXLEN_ID); \
    DST[MESSIP_MAXLEN_ID] = 0;
Definition at line 203 of file messip_private.h.
Referenced by messip_buffered_send(), messip_channel_connect(), messip_channel_create(), messip_channel_delete(), messip_channel_disconnect(), messip_channel_ping(), messip_connect(), messip_death_notify(), messip_receive(), messip_reply(), messip_send(), messip_timer_send(), ping_reply(), and reply_to_thread_client_send_buffered_msg().
Typedef Documentation
typedef struct messip_mgr messip_mgr_t
Enumeration Type Documentation
anonymous enum
Enumerator
MESSIP_OP_CONNECT
MESSIP_OP_CHANNEL_CREATE
MESSIP_OP_CHANNEL_DELETE
MESSIP_OP_CHANNEL_CONNECT
MESSIP_OP_CHANNEL_DISCONNECT
MESSIP_OP_CHANNEL_PING
MESSIP_OP_BUFFERED_SEND
MESSIP_OP_DEATH_NOTIFY
MESSIP_OP_SIN
Definition at line 31 of file messip_private.h.
Function Documentation
int messip_writev (SOCKET sockfd, const struct iovec * iov, int iovcnt)
Write data from multiple buffers over a TCP socket.
The main difference with the library function is that this function handles EINTR (signal received while receiving data).
Parameters
sockfd Socket file descriptor
iov pointer vector points to a struct iovec defining address and bytes
iovcnt Number of blocks described into vector iov
Returns
On success, returns the number of bytes written
On error, -1 is returned, and errno is set appropriately
Definition at line 141 of file messip_lib.c.
Referenced by messip_buffered_send(), messip_channel_connect(), messip_channel_create(), messip_channel_delete(), messip_channel_disconnect(), messip_channel_ping(), messip_connect(), messip_death_notify(), messip_reply(), messip_send(), messip_timer_send(), ping_reply(), and reply_to_thread_client_send_buffered_msg().
int messip_readv (SOCKET sockfd, const struct iovec * iov, int iovcnt)
Read data into multiple buffers from a TCP socket.
The main difference with the library function is that this function handles EINTR (signal received while receiving data).
Parameters
sockfd Socket file descriptor
iov pointer vector points to a struct iovec defining address and bytes
iovcnt Number of blocks described into vector iov
Returns
On success, returns the number of bytes read
On error, -1 is returned, and errno is set appropriately
Definition at line 172 of file messip_lib.c.
Referenced by messip_buffered_send(), messip_channel_connect(), messip_channel_create(), messip_channel_delete(), messip_channel_disconnect(), messip_channel_ping(), messip_connect(), messip_death_notify(), messip_receive(), and messip_send().