messip: messip_utils.c File Reference
messip_utils.c File Reference
MessIP : Message Passing over TCP/IP Copyright (C) 2001-2007 Olivier Singla http://messip.sourceforge.net/.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <errno.h>
#include <stdarg.h>
#include <sys/types.h>
#include <signal.h>
#include <assert.h>
#include <unistd.h>
#include <getopt.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include "messip.h"
Functions
int read_etc_messip (char *hostname, int *port_used, int *port_http_used)
static float cpu_clock_speed (void)
float get_cpu_clock_speed (void)
Detailed Description
MessIP : Message Passing over TCP/IP Copyright (C) 2001-2007 Olivier Singla http://messip.sourceforge.net/.
TBD
Definition in file messip_utils.c.
Function Documentation
int read_etc_messip (char * hostname, int * port_used, int * port_http_used)
Definition at line 29 of file messip_utils.c.
Referenced by messip_connect().
static float cpu_clock_speed (void) static
Definition at line 87 of file messip_utils.c.
Referenced by get_cpu_clock_speed().
float get_cpu_clock_speed (void)
Definition at line 129 of file messip_utils.c.
References cpu_clock_speed().